# Generated by Django 5.2.6 on 2025-09-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('category', models.CharField(choices=[('TS', 'T-shirt'), ('MV', 'Marvin'), ('SH', 'Shoe'), ('HT', 'HAT'), ('HD', 'Hoodie')], default='TS', max_length=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
